# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72697f0a660c4f63e91c16123277b2501bb177d82c452d0cd5ba33a98d4c3b4bd4867a49ccc8010fcb3e894015171af45bff943f32f6b22f7794a7d84cbf05c7

test:
  secret_key_base: 8752c5b15b8ec21cd51f888b373a88ab75350133049c4b4fa7acacbfb8f32c7929100dab385e9069d49a1f4f85f44a44808a486bfcfdc4bc3af3efbabb1710bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
